
taxonomy_db_sources:
  # note: obtain the URL by querying https://api.plutof.ut.ee/v1/public/dois/?format=api&identifier=<DOI>
  # see also https://github.com/bokulich-lab/RESCRIPt/issues/123
  unite_eukarya_refs:
    type: unite_otus
    version: "9.0"
    date: 2022-11-29
    reference: https://doi.org/10.15156/BIO/2483917
    url: https://files.plutof.ut.ee/public/orig/8F/FC/8FFCC8A730E50FEEF8CFFEEFEF02A22FBCF7E02B7FD31C6649754834D2CB0E6F.tgz
  unite_eukarya_all:
    type: unite_otus
    version: "9.0"
    date: 2022-11-29
    reference: https://doi.org/10.15156/BIO/2483918
    url: https://files.plutof.ut.ee/public/orig/71/E6/71E68A5DD3F5C311F913757F9E7CA2508430F9400C14413ADA08A0BB33169BB4.tgz
  Midori_COI:
    type: midori
    reference: https://doi.org/10.1002/edn3.303
    url: http://www.reference-midori.info/forceDownload.php?fName=download/Databases/GenBank256/QIIME/uniq/MIDORI2_UNIQ_NUC_GB256_CO1_QIIME
  Midori_16S:
    type: midori
    reference: https://doi.org/10.1002/edn3.303
    url: http://www.reference-midori.info/forceDownload.php?fName=download/Databases/GenBank256/QIIME/uniq/MIDORI2_UNIQ_NUC_GB256_lrRNA_QIIME
  # Midori_COI_sp:
  #   type: midori
  #   reference: https://doi.org/10.1002/edn3.303
  #   url: http://www.reference-midori.info/forceDownload.php?fName=download/Databases/GenBank256/QIIME_sp/uniq/MIDORI2_UNIQ_NUC_SP_GB256_CO1_QIIME
    url: http://www.reference-midori.info/forceDownload.php?fName=download/Databases/GenBank256/QIIME/uniq/MIDORI2_UNIQ_NUC_GB256_lrRNA_QIIME
  Midori_12S:
    type: midori
    reference: https://doi.org/10.1002/edn3.303
    url: http://www.reference-midori.info/forceDownload.php?fName=download/Databases/GenBank256/QIIME/uniq/MIDORI2_UNIQ_NUC_GB256_srRNA_QIIME
